### PR TITLE
Add setUsePrototypes() method

### LINKED ISSUE #392: Ability to force serializer write all values
Currently there is no ability to force artemis serializer to write all values (0 for int, false for boolean are omitted).

### PR DESCRIPTION
**Pull request by nikoliazekter**
Resolves #392

### CODE REVIEW

**Comment by junkdog** [comment]
looks like sonatype was down and hence the tests failed (at least, it happened locally when I tried deploying).

Could you update the non-libgdx backend too? That should trigger another build as well.

**Comment by nikoliazekter** [comment]
I created new pull request. Probably that's not what I had to do ;)

**Comment by junkdog** [comment]
> Probably that's not what I had to do ;)

close enough ;) weird about the failing tests. hmm.

**Comment by junkdog** [comment]
:cookie: thanks

**Pull request merged**
