### PR TITLE
Better fluent api for aspects

### PR DESCRIPTION
**Pull request by ollipekka**
Hello, 

I got tired of the eclipse warnings for varargs. I improved the fluent api for aspects a bit so that we can avoid varargs and do:
```
aspect.all(One.class).all(Two.class)
```

The new functions need better naming, too. I also added new function Aspect.empty() to create empty AspectBuilders.

I had pretty hard time setting up the project. Ideally I'd need someone to guide me through setting up the project so that it compiles (I get maven plugin error) or test this pull request for me so that i compiles. Non-compiling maven projects are a mess.

### CODE REVIEW

**Comment by Namek** [comment]
tabs vs spaces.

**Comment by DaanVanYperen** [comment]
Mind posting a bug report with the plugin error?

**Comment by ollipekka** [comment]
See any other spaces? I also fixed few other compiler warnings. Not sure if that messes up anything since I still can't get maven project and GWT to compile.

**Comment by Namek** [comment]
That's cleaner but it should be one commit instead of two (for "Cleaning"). I mean - git shows that you changed whole `Aspect` class and we can't easily see what were real changes in there.

**Comment by ollipekka** [comment]
To be honest, I'd throw away the comments on most classes where they are similar to Aspect. They aren't really helpful at all. The method naming in Aspect could use more thought because it's unclear at the moment. Any ideas?

**Comment by ollipekka** [comment]
Redid the PR: first commit b38ed28 contains the changes to the aspect. Second commit 0c265e1 contains changes caused by it and cleanup.

**Comment by junkdog** [comment]
Hi. sorry for not attending this sooner.

The aspect methods you've added are actually very similar (or identical) to the ones which were removed in 0.7.0 - they complicated/broke the weaving processing, bytecode introspection (dependency matrix) and, in effect, are identical to the methods without the initial component type parameter.

While I agree that it'd be nice to get rid of the warnings, I think it would be better accomplished by relying on `@SafeVarargs`. When I attempted it previously, something broke - either the android or gwt build, I don't remember which. It should however be possible to fix, as I believe ashley have done so.

**Comment by junkdog** [comment]
> I was thinking of binary operators (and, or, not), but not sure if they're any better. Any ideas?

Tricky, but unless there's a really compelling reason for changing them, I'd prefer not to introduce any more breaking API changes prior to 1.0.0 (meaning anything new will happen after that).

I, personally, think that inclusion and exclusion (no bearing on actual names, just what they do) suffice - I don't think I've used `any(Component...)` at all in recent projects. They're a weird kind of glue. Removing `any()` would break a lot of existing code though, so it stays for historical reasons.

**Comment by DaanVanYperen** [comment]
@junkdog relevant Ashley commit https://github.com/libgdx/ashley/commit/fc00f2b3c85470cb8690b98e0e3a24619bafa34b
.

**Comment by junkdog** [comment]
> "Android 4.4+"

It might have been that it was added with the android dev tools coinciding with the 4.4 release? `final` seems to do something, at least.

**Comment by DaanVanYperen** [comment]
@ollipekka thanks for your effort, hope the @SafeVarargs suffices for now!

**Pull request closed without merging**
