### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by nicolaichuk**
@junkdog, please review and merge with upstream.

### CODE REVIEW

**Comment by junkdog** [comment]
Nice, looking good (heh, java 6 lingered for slightly to long)!

One small thing though, could we drop https://github.com/junkdog/artemis-odb/pull/492/commits/0954228b28d22821fb6d2429dc9160fc6e731339 (IntBag / for-each)? While convenient, it implies a copy of the underlying array, and for-eaching boxes each `int` < 127 as an `Integer` instance (unless you're on the JVM and can set `-XX:AutoBoxCacheMax` to a more appropriate value).

**Comment by nicolaichuk** [comment]
@junkdog, you are maintainer of artemis-odb, and if you tell me to drop 0954228 (IntBag / for-each), then I will certainly revert it.

But I think that it would be better to describe it all in the comments to the method,
and leave it as syntactic sugar, because it is convenient for use in code that not require performance.

**Comment by nicolaichuk** [comment]
@junkdog, What's your decision about 0954228 (IntBag / for-each)?

**Comment by sreich** [comment]
I agree with @junkdog , I don't see what more that does, there is already public get data int[] so you should be able to use that for whatever you want.

If you want to do anything else you can make your own utility function easy enough. If you are concerned about syntactical sugar you can use a language which supports it such as kotlin, which would benefit other libraries you use, too. Then you could easily do bag.foo() which is a static function (extension function).

**Comment by junkdog** [comment]
Sorry, forgot about this, crunchy times.

I think a simple wrapper for an ad-hoc iterator is less controversial; a class wrapping an `int[]` + range, and providing `int next()`/`boolean hasNext()`. This removes the `Integer` boxing, but is a bit more verbose than a for-each loop.

An `IntIterator` is an edge-case for artemis. It feels like something which is already provided by a lot of other frameworks (though I thought libgdx had one; seems I was wrong). 

```java
IntIterator it = new IntIterator(ids.getData(), 0, ids.size());
while (it.hasNext())
    doSomething(it.next());
````

with some project plumbing, it could be shortened to something like:

```java
for (IntIterator it = iterate(ids); it.hasNext();)
    doSomething(it.next());
```

**Comment by sreich** [comment]
Libgdx has IntArray, which avoids boxing and can be unordered they implement iterable for everything I think, with the footnote that they cache their iterators instead of allocate, which leads to problems with nested loops.

**Comment by junkdog** [comment]
Hmm, I thought so too, but I [can't find it](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/IntArray.java). Was the iterator thing removed perhaps?

**Comment by sreich** [comment]
Oh interesting. Guess it was always just Gdx.Array that has the iterator

**Comment by nicolaichuk** [comment]
remove getActualData() from IntBag
add IntBagIterator

@junkdog, @sreich, please review.

**Comment by Namek** [comment]
@nicolaichuk it would propose to cover that iterator with some unit tests. Add few then remove few (less than added before) entities and then go with iterator.

**Comment by DaanVanYperen** [comment]
Oops, broke this. I'll merge manually.

**Comment by DaanVanYperen** [comment]
Merged, added tests and fixed small bug. Suspect IntBagIterator will see some evolution but leaving it in for now. Thanks for the contribution @nicolaichuk!

**Comment by nicolaichuk** [comment]
@DaanVanYperen, thanks.

**Pull request merged**
