### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by DaanVanYperen**
2.2.0 is ready to be released! Tag it and bag it when you're ready!
Edit: Compile with JDK 8!!! 9+ will break the GWT tests.

- **BREAKING CHANGES**
  - Web backend upgraded to GWT `2.8.1` (LibGDX is blocking `2.8.2`).
  - Serialization modules that depend on libGDX now require `1.9.9`.

#### Other
- **Global option to delay component removal until all subscriptions have been notified.**
    `new WorldConfigurationBuilder().alwaysDelayComponentRemoval(true)` 
- **Annotation driven aspects** (`@All`, `@Exclude`, `@One`).
  - Annotate BaseEntitySystem subclass, alternative to constructor argument.
  - Adds DI of `Archetype`, `Aspect`, `Aspect.Builder` and `EntitySubscription` fields.
- **Fluid entities** quality of life changes.
  - To enable fluid entities in your world, best practice register `FluidEntityPlugin` instead of `SuperMapper`.
  - `FluidEntityPlugin` generated as part of the fluid generation process.
  - Added `FluidIteratingSystem`.
  - Generate class C containing all fluid component class literals. (not usable in annotations, sorry).
  - Convenience methods to find entities:
    - by group `for ( E e : E.withGroup("enemy") ) { .. }`
    - by tag `E player = E.withTag("player");`
    - by aspect `for ( E e : E.withAspect(Aspect.all(Pickup.class, Pos.class)) ) { .. }`
    - by component `for ( E e : E.withComponent(Pickup.class) ) { .. }`
  - Allow plugins for fluid interface generation.
    - Override type handling via FieldProxyStrategy. (Want extra methods for LibGDX's `Pos2`? Now you can!)
- **Support for abstract plugins** with multiple possible implementations.
      For example, a logging plugin might have multiple implementations (TinyLog, SLF4J+??, LibGDX). 
      As a plugin developer, we want to be able to refer to the generic facade (LoggingPlugin) and 
      throw a warning when no specific implementation has been registered.
- **Fix**: Better document side effects of ComponentMapper and EntitySubscription.      
- **Fix**: Unchecked warning in `SuperMapper`.
- `World` instances can now inject themselves (`World::inject`)

### CODE REVIEW

**Comment by DaanVanYperen** [comment]
Looks like GWT is still on 2.8.0 in the quickstart tool, gimme a sec.

**Comment by DaanVanYperen** [comment]
Go ahead!

**Comment by junkdog** [comment]
:cookie: 

2.2.0 is pushed to maven repo, javadocs deployed + wiki version references updated.

**Comment by DaanVanYperen** [comment]
Awesome!

Did you have any issues doing the release? I just spent two hours fighting
mvn release git auth. The last release was in 2017 :shame:

Btw libGDX discord has an active #ecs channel with odb users as well, worth
checking out.

Daan

**Comment by DaanVanYperen** [comment]
I was looking at Ashley and they don't even provide ids for entities since
0.6. Using the weird hash/bag/set/dwarf/goblin collections from libgdx. I
wonder what their performance is like nowadays.

Oh! Would be cool if we can add big-O for our basic operations to
the Ashley comparison sheet, I bet we come out better. I assume odb mostly
does O(1)?

|  | ashley | us |
Add entity | O(?) | O(?) |
Remove entity | O(?) | O(?) |
Add component | O(?) | O(?) |
remove component  | O(?) | O(?) |
component lookup | O(?) | O(1) |
update subscriptions? | O(?) | O(?) |
etc.

**Comment by junkdog** [comment]
> Did you have any issues doing the release? I just spent two hours fighting mvn release git auth. The last release was in 2017 :shame:

Hmm, no - I take you're doing it from the terminal - as in not travis? What problem are you having?

My workflow is `mvn release:clean`, `mvn release:prepare`, `mvn release:perform` - here it prompts for password to sign with PGP/fetches it from the keychain.



> Would be cool if we can add big-O for our basic operations to the Ashley comparison sheet,

Hmm, hard to translate a lot of stuff. Artemis adds a lot of extra steps which aren't present in ashley.

Create/remove operations in O(1), _but_ then incurs an O(N) when requesting an updated `EntitySubscription::getEntites`, whereas Ashley does remove in O(N) and create in O(1) (iirc).

Ashley and artemis technically both have O(1) aspect query (as in, checking the entity composition vs system's aspect), but ashley compares composition vs 3 bitsets while artemis uses the entity compositionId and matches it against a single bitset in EntitySubscription (`aspectCache[compositionId]` - `validCompositions` is a more descriptive name).

> what their performance is like nowadays.

I think they take an unnecessary performance hit from having Entity own its entities. Feels pretty expensive considering how entity systems favor iterating over components by type, rather than sequentially processing each entity sequentially once per frame.

**Comment by DaanVanYperen** [comment]
Thought EntitySubscription wasn't brute-force but instead scans touched
entities from purgatory/changed/spawn array? If that's the case wouldn't it
still technically be a delayed O(1)?

Was taking a stab at updating the benchmarks to 2.2.0 / 0.7.3 respectively
(Abandoned cause the linux-scripts are being poopnoses) and id's were gone
in Ashley compared to 0.6, looks like they internally use ObjectSet for
part of it. Probably use more hodgepodge-hash collections.
"contains and remove  (typically O(1), worst case O(log(n))). Add may be a
bit slower."  according to docs.

Daan

**Comment by junkdog** [comment]
> Thought EntitySubscription wasn't brute-force but instead scans touched
> entities from purgatory/changed/spawn array? If that's the case wouldn't it
> still technically be a delayed O(1)?

I meant [EntitySubscription::getEntities](https://github.com/junkdog/artemis-odb/blob/93c653e1dfc8176fb5934908ae358b5d1686caf3/artemis-core/artemis/src/main/java/com/artemis/EntitySubscription.java#L55:L56) rebuilds the backing IntBag from scratch each time from from N entities.



> Ashley compared to 0.6

1.6! 

Yeah, I remember now that the omission of id messed up the benchmark impl.

**Comment by DaanVanYperen** [comment]
There's a lot of interest in the benchmarks on Discord btw, would be
awesome if we can get those going again.

I know benchmarks are fluff, it does seem to be important for peeps picking
a framework. A 'ms per frame on Y systems vs X entities' on
<platformspecs>' might be interesting as well, bring it into perspective.

Most of my games are 20-30 systems so interested to see what the cost is
there. Come to think of it wouldn't hurt getting Fluid benchmarked.

**Comment by junkdog** [comment]
Should probably revisit the benchmarks; I think it'd be better to generate the benchmarks from some sort of templates (either VTL or something custom but to the point). They're a PITA to update as-is.

I'm setting aside some :moneybag: for a desktop; rather not run the benchmarks on the laptop, it throttles too much to be reliable/me to be comfortable. That's another 2-3 months away though. 

The overhead from 20-30 systems is negligible. At feo/last place, we had ~80 components, ~60 systems - don't recall how many EntitySubscriptions - but those are arguably equatable to systems from a benchmark POV. Then there's the matter of systems sharing the same EntitySubscription; they share the same entity IntBag/only constructed once.

Iteration and propagating 

Found an old screenshot, was hoping I had one with the system profiler running. Should have one tucked away, somewhere.

fly-from-mailbox

(memories)
 
That said - running some sort of benchmarks on GWT and android would be very interesting too.

**Comment by DaanVanYperen** [comment]
I've got a gaming rig already so no need to wait! ;)

  If it is easy to run we could probably gather a couple profiles. As it
stands it isn't a one-click-run kind of deal.

**Pull request merged**
