### PR TITLE
World is now injected with world.inject(object) #479

### PR DESCRIPTION
**Pull request by piotr-j**
Systems still use setWorld() as ComponentManager and EntityManager are marked as SkipWire.

### CODE REVIEW

**Comment by junkdog** [comment]
I played around with the errors a bit / trying to go to bed. (ping @schosin) 

I `@SkipWire:d` the necessary `world` fields in https://github.com/junkdog/artemis-odb/tree/piotr-j-inject-world + BaseSystem's `world` looked like it wanted a `@SkipWire` too, as it gets one regardless.

**Comment by schosin** [comment]
I have it implemented differently. See #479 and schosin/artemis-odb@df59213675ff5086aa494142fa497372f49638d1

Instead of using @SkipWire everywhere I checked whether the world field was null by passing the target into ```FieldResolver.resolve``` and checking ```field.get(target) == null```. Field needs to be set accessible.
I think doing that in @piotr-j 's implementation would be the best solution. 

When I commited it I only ran the tests in artemis-odb + a new test for injecting world. Might need to check artemis-odb-gwt. When I tried to import it it's missing all import statements and everything's red.

**Comment by schosin** [comment]
Looking at @piotr-j 's WiredTest, I think the wired world should be a different one if a second world was registered in the first one. I commited a change to my fork and wrote the test for that. 
See here: schosin/artemis-odb@4d329d4acb939133c2456d222599fdbe9c5b8346

**Comment by piotr-j** [comment]
Multiple worlds is not something Ive given a whole lot of thought into. So when we inject `@Wire world` we  use registered world first, if it is set. Otherwise with missing annotation or not registered other world we use owner world. sounds about right?

**Comment by piotr-j** [comment]
Ive fixed multiple worlds @schosin way. All tests pass now.

**Comment by junkdog** [comment]
Problem with this approach is that we introduce a different approach when injecting `World:s` - so the user has to remember that all injectables _except_ for `World` is injected each time inject is called.

I personally think that `@SkipWire` is more straight-forward as it then works the same for all injectable types. Consider unjecting a Context-pojo multiple times - on subsequent `World::inject`, all references except World are updated.

**Comment by junkdog** [comment]
:cookie: 

nice! I like merging before going to bed :)

**Comment by junkdog** [comment]
thanks!

**Pull request merged**
