### PR TITLE
Deprecate counters in EntityManager

### PR DESCRIPTION
**Pull request by antag99**
This pull request reverts the changes introduced by e1492ccb0b193609c06cbc720b47de18377e8a9f and deprecates the methods instead.

### CODE REVIEW

**Comment by junkdog** [comment]
Better leave the methods deprecated and always have them return 0. Could you do another commit and remove the fields altogether?

**Comment by antag99** [comment]
All right, I stubbed the methods to always return `0`. Btw, quit sneaking changelog updates into unrelated commits... :wink:

**Comment by junkdog** [comment]
I didn't want to kill the kittens by rewriting history!

cat

**Comment by junkdog** [comment]
:cookie:

**Comment by DaanVanYperen** [comment]
noooooooooooooooooo I love kittens. :(

**Pull request merged**
