### PR TITLE
Fluid API

### PR DESCRIPTION
**Pull request by DaanVanYperen**
Working. Components on classpath go in, fluid interface comes out. Room for performance improvements in the plugin. See #458 for more information.

**Getting started**
1. Install this branch locally. (specifically `artemis-fluid` and child modules).
2. https://github.com/junkdog/artemis-odb/wiki/Fluid-Entities
# Todo
- [x] Generation of E.class.
  - [x] Efficient instancing of E class instances
  - [X] Basic accessors from #458 (see below)
- [X] Generation of SuperMapper.class
  - [X] Provide access to all ComponentMappers
- [X] Basic maven and gradle plugins
  - [x] Performance tuned component collection.
  - [X] Ambiguous field/method fail early.
  - [X] Generation to agnostic model
  - [X] Example code generation implementation with JavaPoet.
  - [X] Scan components on classpath, including libraries
- [X] Multiworld support.
- [x] Documentation (Wiki)

### CODE REVIEW

**Comment by shatterboom** [comment]
`Pos::set(x,y)`  generates `E::pos(p0,p1)` It would be nicer to use the same parameters name as the set method.

**Comment by DaanVanYperen** [comment]
@junkdog if you're happy where it sits give it a PR so I can start working on other things D:

**Comment by DaanVanYperen** [comment]
@shatterboom since we reflect over class files there's no easy way to obtain parameter names, unless compiling with debug information or running sort of metadata weaving utility. It's part of #461.

**Comment by DaanVanYperen** [comment]
@junkdog :'(

**Comment by junkdog** [comment]
>  on Sep 11

ewww.... there should have been more :cookie: :cookie: :cookie: and much less :clock1:

**Comment by junkdog** [comment]
want to do the spaces to tab conversion? feels revisionist to commit it myself.

**Pull request merged**
